name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-v2-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
